logging:
    level:
        com:
            fluidcodes:
                crm: trace
        org:
            hibernate:
                SQL: info
                type: info
server:
    port: 8080
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        initialization-mode: always
        password: root
        url: jdbc:postgresql://localhost:5432/fc_crm
        username: root
    jpa:
        hibernate:
            ddl-auto: update
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        properties:
            hibernate:
                dailect: org.hibernate.dialect.PostgreSQLDialect
                event:
                    merge:
                        entity_copy_observer: allow
        show-sql: true
    security:
        user:
            name: '"admin"'
            password: '"admin"'
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 50MB
            max-request-size: 60MB

